name: Docker Build and Push

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/timeguarana/workspace
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=2023.1.4,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=timeguarana/workspace
            org.opencontainers.image.description=Base image for development environments
            org.opencontainers.image.version=2023.1.4

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./workspace
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
